apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: test-backstage-template-with-numbers
  title: Number
  description: Numbers
  tags:
    - recommended
    - react
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide a number
      required:
        - port
      properties:
         port:
          title: Port
          type: integer
          default: 8080
          description: Development port of the api service (8080 is express default)
          pattern: ^([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$
  steps:
    - id: lognumber
      name: log number
      action: blam:log-number
      input:
        number: '{{ json parameters.port }}'
